### PR TITLE
support Python 3.4

### PR DESCRIPTION
**Pull request by hjacobs**
`exist_ok` was introduced in 3.5: https://docs.python.org/3/library/pathlib.html#pathlib.Path.mkdir

### CODE REVIEW

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
now also has a test for the relevant code path and runs with 3.4 on Travis..

**Comment by ideahitme** [comment]
👍

**Pull request merged**
